
package com.oracle.xmlns.apps.projects.billing.workarea.invoice.invoiceservicev2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProjectContractInvoiceService", targetNamespace = "http://xmlns.oracle.com/apps/projects/billing/workarea/invoice/invoiceServiceV2/", wsdlLocation = "https://egup-dev9.fa.us2.oraclecloud.com/fscmService/ProjectContractInvoiceService?WSDL")
public class ProjectContractInvoiceService_Service
    extends Service
{

    private final static URL PROJECTCONTRACTINVOICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROJECTCONTRACTINVOICESERVICE_EXCEPTION;
    private final static QName PROJECTCONTRACTINVOICESERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/projects/billing/workarea/invoice/invoiceServiceV2/", "ProjectContractInvoiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://egup-dev9.fa.us2.oraclecloud.com/fscmService/ProjectContractInvoiceService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROJECTCONTRACTINVOICESERVICE_WSDL_LOCATION = url;
        PROJECTCONTRACTINVOICESERVICE_EXCEPTION = e;
    }

    public ProjectContractInvoiceService_Service() {
        super(__getWsdlLocation(), PROJECTCONTRACTINVOICESERVICE_QNAME);
    }

    public ProjectContractInvoiceService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROJECTCONTRACTINVOICESERVICE_QNAME, features);
    }

    public ProjectContractInvoiceService_Service(URL wsdlLocation) {
        super(wsdlLocation, PROJECTCONTRACTINVOICESERVICE_QNAME);
    }

    public ProjectContractInvoiceService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROJECTCONTRACTINVOICESERVICE_QNAME, features);
    }

    public ProjectContractInvoiceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjectContractInvoiceService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProjectContractInvoiceService
     */
    @WebEndpoint(name = "ProjectContractInvoiceServiceSoapHttpPort")
    public ProjectContractInvoiceService getProjectContractInvoiceServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/projects/billing/workarea/invoice/invoiceServiceV2/", "ProjectContractInvoiceServiceSoapHttpPort"), ProjectContractInvoiceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjectContractInvoiceService
     */
    @WebEndpoint(name = "ProjectContractInvoiceServiceSoapHttpPort")
    public ProjectContractInvoiceService getProjectContractInvoiceServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/projects/billing/workarea/invoice/invoiceServiceV2/", "ProjectContractInvoiceServiceSoapHttpPort"), ProjectContractInvoiceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROJECTCONTRACTINVOICESERVICE_EXCEPTION!= null) {
            throw PROJECTCONTRACTINVOICESERVICE_EXCEPTION;
        }
        return PROJECTCONTRACTINVOICESERVICE_WSDL_LOCATION;
    }

}
